# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b604bcb8589b5c8171814656a502d08"
name = "api_vendus"
handle = "api-vendus"
application_url = "https://graphics-care-film-surgery.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, write_inventory, read_inventory, write_orders, read_orders, write_customers, read_customers, read_locations, read_markets_home, read_publications, write_publications"

[auth]
redirect_urls = ["https://graphics-care-film-surgery.trycloudflare.com/auth/callback", "https://graphics-care-film-surgery.trycloudflare.com/auth/shopify/callback", "https://graphics-care-film-surgery.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
